### ISSUE TITLE
crashed world? 

### ISSUE THREAD

**Issue by Mementh** [juraj-hrivnak/Underdog#19]
trying to attach

**Comment by juraj-hrivnak** [comment]
Maybe this is the cause of the lag `AIImprovements-1.12.1-0.0.1b1`.
It should be `1.12`, not `1.12.1`.

**Comment by juraj-hrivnak** [comment]
Ahah, it can also be caused by `In Control`.
I added some new water spawns to the ocean. So maybe it went out of the cap?

**Comment by Mementh** [comment]
[minecraft crash.zip](https://github.com/juraj-hrivnak/Underdog/files/6916340/minecraft.crash.zip)
[minecraft crash.z01.zip](https://github.com/juraj-hrivnak/Underdog/files/6916344/minecraft.crash.z01.zip)

**Comment by juraj-hrivnak** [comment]
It will be fixed in dev.
