### ISSUE TITLE
Clay bucket milk use

### ISSUE THREAD

**Issue by Kr8vzn** [juraj-hrivnak/Underdog#23]
Using clay bucket to get milk from cow is not usable without forestry bottler. There are no recipes to use it.

Recipes should be similar to those for iron bucket. This would make clay bucket more useful before iron is produced.

**Comment by juraj-hrivnak** [comment]
Clay bucket from ceramics will be removed in new version, also with the whole Ceramics mod. Raplacement for it will be Pyrotech clay bucket, so we will see if it have the same issue.

**Comment by juraj-hrivnak** [comment]
Implemented in dev.
