### ISSUE TITLE
Milk turns into water when using a bottle

### ISSUE THREAD

**Issue by Kr8vzn** [juraj-hrivnak/Underdog#24]
**Describe the bug**
Holstein milk put in a hole in ground becomes water when filling glass bottle

- **To Reproduce**
put milk in hole. Click on it with glass bottle

**Comment by juraj-hrivnak** [comment]
This seems to be a Forge bug when any fluid of material water will return the same water bottle.

**Comment by juraj-hrivnak** [comment]
Picking up milk using a bottle will be no longer possible, and this is now the only way to get a milk bottle:
![2022-11-02_23 21 06](https://user-images.githubusercontent.com/71150936/199613729-32e37c09-d908-4095-81e8-e8bc3304daa9.png)
