### ISSUE TITLE
Underdog GUI Textures Failing to Load

### ISSUE THREAD

**Issue by AdroitErudite** [juraj-hrivnak/Underdog#27]
**Describe the bug**
The textures for the Underdog gui are missing in game, causing the magenta and black 'texture' to appear. Java cannot locate them despite being in the mod pack folder

- **To Reproduce**
Extracting the Underdog pack override into installation, then launching minecraft.

**Expected behaviour**
Java should be able to find the files present in the \oresources\modpack\textures\gui' folder and display the gui

**Screenshots**
![2021-12-14_17 50 33](https://user-images.githubusercontent.com/78564758/146092117-8d2f7a68-efb4-4b2a-8158-abb6ee3f8a1d.png)
![2021-12-14_17 50 45](https://user-images.githubusercontent.com/78564758/146092119-f1dd5c70-451f-42ab-975a-21964b002f0d.png)
![2021-12-14_17 50 50](https://user-images.githubusercontent.com/78564758/146092120-60fd8f0f-45eb-4da5-8bc1-8d0afbfaa57f.png)
![2021-12-14_17 51 00](https://user-images.githubusercontent.com/78564758/146092121-53ff5897-316f-4e1c-8a3c-684a322b89ee.png)

**Additional context**
[debug.log](https://github.com/juraj-hrivnak/Underdog/files/7715240/debug.log)
[latest.log](https://github.com/juraj-hrivnak/Underdog/files/7715241/latest.log)
In the debug it says that it fails to locate the texture in the specified path.

**Comment by juraj-hrivnak** [comment]
I will try moving the GUI resources from /oresources to resources in the new version.

**Comment by juraj-hrivnak** [comment]
But, from a brief look, it looks like none of the oresources have loaded.

**Comment by AdroitErudite** [comment]
I believe it was the process of using the server zip file with the overide folder from the curseforge download page. A few other things are missing too, lile the title screen not updating to Underdog, the pollution renders, and the atmos pack is missing as well.
I use the 'old' vanilla launcher, and MultiMC worked fine. I think this issue may be limited to the .zip files there because copying and pasting the installation made by MultiMC into Vanilla carries over everything correctly.
So if it is not an actually Underdog issue, you can close this issue, it might be just that the full zip should be on the curseforge page instead of just override.

**Comment by juraj-hrivnak** [comment]
@AdroitErudite Check if you have resource loader instaled. Because that mod load all the textures that are missing.

Btw you probably misunderstood what server pack is. You should **not** use the server pack on your computer (as a client).
All these mods will crash on the server: 
```
    Custom Main Menu
    Resource Loader
    Matmos
    Journey Map
    Journey Map Stages
    Tips
    InvMove
```
But are necessary for the client!

Use the file marked in green:
![](https://user-images.githubusercontent.com/71150936/146275095-c75efb0a-2e4d-4eba-88b1-3bc6e582f07e.png)

**Comment by juraj-hrivnak** [comment]
You could try the new release!

**Comment by AdroitErudite** [comment]
Sounds good! But does the zip file download everything upond launch? It is only 16MB and is missing all the other mods and files, etc.

**Comment by juraj-hrivnak** [comment]
That stuff gets downloaded by the launcher.

**Comment by juraj-hrivnak** [comment]
I think this can be closed now. 
Download the latest `beta 2.0.3` and you should be all good! (Just don't use the server-pack)
Also, I recommend you to use this launcher: https://download.curseforge.com/
