### ISSUE TITLE
Fishing Made Better startup crash

### ISSUE THREAD

**Issue by MoonlitFirebrand** [juraj-hrivnak/Underdog#32]
**Describe the bug**

Changing certain controls from in-game causes the modpack to stop launching successfully on subsequent launches, due to an error with Fishing Made Better

**- To Reproduce**
Steps to reproduce the behaviour:
Please refer to the attached options.txt file for a complete list of keybind changes, which is left-hand friendly
[options.txt](https://github.com/juraj-hrivnak/Underdog/files/8527563/options.txt)

**Expected behaviour**

The game should launch correctly and arrive at Minecraft's main menu screen

**Screenshots**

![Screenshot (404)](https://user-images.githubusercontent.com/103981387/164380125-63465e71-36ba-42b2-8e27-bf900e9527ab.png)

**Additional context**

Switching the main hand to the left hand does not affect the modpack's ability to launch
Both altering and not-altering Fishing Made Better keybinds does not inherently affect the modpack's ability to launch
- Relevant crash report: 
[crash-2022-04-18_20.23.06-client.txt](https://github.com/juraj-hrivnak/Underdog/files/8527626/crash-2022-04-18_20.23.06-client.txt)

**Comment by juraj-hrivnak** [comment]
Install the latest beta instead of the release which is no longer supported. It’s confusing, I know. I will have to do something with the versioning on CurseForge.
