### ISSUE TITLE
Animated textures won't work with Optifine installed

### ISSUE THREAD

**Issue by Deltacleic** [juraj-hrivnak/Underdog#35]
**Describe the bug**

The streams water along with the pyrotech firepit fire is not animated whatsoever.
- **To Reproduce**
Steps to reproduce the behaviour: 
1. Find stream mod streams - view unanimated water
2. Place logpile in standard format for pit burning and ignite - view unanimated fire
**Expected behaviour**

Stream water and fire to be animated.
**Screenshots**

![2022-08-04_19 13 06](https://user-images.githubusercontent.com/79710042/182970557-ada66b2d-49b8-40e7-a8b7-b93c36ae77c0.png)

**Additional context**

**Comment by Deltacleic** [comment]
Seems like all the animation issues are resolved when loliASM is removed.

**Comment by Deltacleic** [comment]
Issue fixed when editing the config file of loliASM and setting OnDemandAnimations to false as seen in [https://github.com/LoliKingdom/LoliASM/issues/109](#109)

Also turn off smart animations in Optifine if it is installed

**Comment by juraj-hrivnak** [comment]
Thanks! So, this is optifine conflict, good to know.

I will reopen it until it get fixed in the modpack.
