### ISSUE TITLE
Pyrotech's Coal Coke block is not a valid fuel in the IE's Blast Furnace

### ISSUE THREAD

**Issue by WesternFreak** [juraj-hrivnak/Underdog#37]
**Describe the bug**
PyroTech's Coal Coke block is not a valid fuel in the Immersive Engineering Blast Furnace

**Steps to reproduce the behaviour:**
Refractory Burning produces IE Coal Coke, which can be compressed in the Mechanical Compactor into a block form, in which it becomes **Pyrotech** Coal Coke.

**Expected behaviour**
If the BF accepts IE's Coal Coke item as a valid fuel then it'd be expected that Pyrotech's Coal Coke block would also be valid as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/4205706/184239614-ccff4d1e-a6de-493f-95bb-b598d433ffc6.png)
Pyrotech's Coal Coke block can't be used (notice the red overlay on the slots when using SHIFT)

![image](https://user-images.githubusercontent.com/4205706/184239794-17efccea-6946-43a6-9345-af5e49051565.png)
Immersive Engineering's Coal Coke block is a valid item for the fuel slot (cheated in to test)

**Additional context**
Underdog v3.0.1

**Comment by KaleThyself** [comment]
That's odd, I can use coal coke from Pyrotech perfectly fine for steel production.

**Comment by KaleThyself** [comment]
Okay, disregard my previous message as I was incorrectly remembering. When pit/refractory burning, the output is IE Coal Coke. However, when compacting that IE Coal Coke with Pyrotech's Mechanical Compactor, it turns into Pyrotech Coal Coke which isn't able to be used with the Blast Furnace. However, to circumvent this, the recipe for IE Coal Coke simply requires a crafting table. 

Two solutions would be to either create an Oredict compatibility for all Coal Coke in the Blast Furnace or simply create a CT recipe to convert between the two types of Coal Coke (Pyrotech/IE).

**Comment by juraj-hrivnak** [comment]
Thanks for the report.
Pyrotech probably doesn’t have oredictonary on that block. But, this reminds me that I should unify all the block, not only this one.

**Comment by juraj-hrivnak** [comment]
Fixed in v3.0.2
