### ISSUE TITLE
Modpack crashes graphics drivers during pre-initialization.

### ISSUE THREAD

**Issue by Allaark** [juraj-hrivnak/Underdog#38]
_**Describe the bug**_
During Pre-Initialization, a mod causes graphics drivers to crash, causing a black screen for a few seconds while the drivers reboot/enter safemode. The bug seems to be caused by the mod Endertech Forge (I might have the name wrong, I am most sure of the words Ender and Forge, but am unsure about the word tech.) or something set to pre-initialize right after it.

_**To Reproduce**_
- 1. Launch the pack
- 2. The pack will begin loading as normal.
- 3. when pre-initializing the mod "Endertech Forge" (or something set to load right after), The screen freezes, then goes dark.
- 4. Upon Re-initialization of graphics drivers, the Minecraft window will be frozen. with a white screen

_**Expected behavior**_
The expected behavior is that pre-initialization and the rest of loading continues as normal, or at the very least throws a readable error.

_**Screenshots**_
![image](https://user-images.githubusercontent.com/92659523/185779549-ca974ae4-c875-4397-87eb-67f79eae7f0f.png)
_The Minecraft window is frozen completely white, and cannot be moved._

_**Additional context**_
My computer runs the Radeon RX 570 Series GPU, and has 8 Gigs of ram.

**Comment by juraj-hrivnak** [comment]
Thanks for the detailed report! I mainly need logs

**Comment by juraj-hrivnak** [comment]
If you are using CurseForge App, try to move to [PolyMC](https://polymc.org/). It might fix the issue.

**Comment by Allaark** [comment]
_**Update**_
Here is the log you are asking for:
[latest.log](https://github.com/juraj-hrivnak/Underdog/files/9389722/latest.log)

**Comment by kylethedragon** [comment]
I'm having the same issue with my drivers crashing when pre-initializing Endertech. I get the same frozen, white screen, and no errors are thrown. I'm running an RX 580 with 8 gigs allocated, so maybe it's related to 500 series AMD cards? Here's my log, I'm hoping it helps.
[latest.log](https://github.com/juraj-hrivnak/Underdog/files/9947083/latest.log)

**Comment by juraj-hrivnak** [comment]
Thanks for providing the log.
There is one concerning thing there: you use really outdated java. Java 8 Update 51 is **7 years** old.
```
Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
```
But other than that, the log says very little to me. There isn't a crash log. It seems that it just stops at pre-init.
You could try to move to a different launcher with the latest java and see if it would work.

**Comment by juraj-hrivnak** [comment]
### The issue

CurseForge launcher uses seven **years old java** by default, which with AMD GPU, causes a crash at pre-initialization.

### Solution

You have to either: **use a different launcher** or **force the CurseForge launcher to use the latest java**.
I recommend you [GDLauncher](https://gdlauncher.com/), [ATLauncher](https://atlauncher.com/downloads) or [Prism Launcher](https://prismlauncher.org/).
