### ISSUE TITLE
Blue square on rocks 

### ISSUE THREAD

**Issue by YUNGHOD** [juraj-hrivnak/Underdog#41]
**Client** 
- [x] MultiMC

**Operating System** 
- [x] Windows

### Latest.log
https://sharetext.me/7orcfnxpfd)

**Describe the bug**
blue square on rocks, when break there are particle effect pop out (unlike not squared one)

**Comment by juraj-hrivnak** [comment]
Can you send me a screenshot? I’m not sure what rock you mean.

**Comment by YUNGHOD** [comment]
https://www.veed.io/view/10b0e9c6-6842-4e33-936e-ae326ee1425a?sharingWidget=true
Also i dont know why the game dont use up idle resources (as u see form top left)

**Comment by YUNGHOD** [comment]
https://www.veed.io/view/10b0e9c6-6842-4e33-936e-ae326ee1425a
Also, idk why the game isnt using idling resources of cpu gpu

**Comment by juraj-hrivnak** [comment]
Duplicate of #35
