### ISSUE TITLE
Dynamic Darkness causes extreme lag

### ISSUE THREAD

**Issue by Geonaut3** [juraj-hrivnak/Underdog#42]
The latest version (0.4.2) of Dynamic Darkness causes excessive amounts of lag. [https://github.com/yamporg/mods/issues/40](https://github.com/yamporg/mods/issues/40)
Downgrading to 0.2.1 fixes the issue

**Comment by juraj-hrivnak** [comment]
Thanks for the report! 
I’ve noticed that the amount of lag increased in the latest releases, but I had no clue that it could be this mod.

**Comment by juraj-hrivnak** [comment]
Fixed in v3.0.2
