### ISSUE TITLE
Game crashes when trying to join the server

### ISSUE THREAD

**Issue by Saamioo** [juraj-hrivnak/Underdog#43]
### Description

tried to join the server and game crashed

### Reproduction steps

a

### The latest.log file

https://gist.github.com/Saamioo/7c22b939727ec95c9782f9b9a6007644

### Launcher

CurseForge

### OS

Windows

**Comment by juraj-hrivnak** [comment]
Thanks!

**Comment by juraj-hrivnak** [comment]
That's not the latest.log. I need the full log.

**Comment by Saamioo** [comment]
https://gist.github.com/Saamioo/2b88ddcf33188381d86133ecf4836703

**Comment by juraj-hrivnak** [comment]
Ok, thanks!

**Comment by juraj-hrivnak** [comment]
It looks like the modpack has not been installed correctly. Some configs did not load properly. Try to download it again.

**Comment by Saamioo** [comment]
Redownloaded, still crashes. also before crash briefly in the chat was some error for crafttweaker
https://gist.github.com/Saamioo/b1a6d2548a7ebed87c1dd5c152cc386c

**Comment by juraj-hrivnak** [comment]
Interesting, can you send me the `crafttweaker.log` then?

**Comment by Saamioo** [comment]
https://gist.github.com/Saamioo/ad388159b867be530b653a7f8b874dc3
there

**Comment by Saamioo** [comment]
also crashes with polymc
https://gist.github.com/Saamioo/a485018a34af66d0700f47ac259b2a1e

**Comment by juraj-hrivnak** [comment]
Okay, thanks for the logs!
This issue appears to be related to the Tabulator mod.

**Comment by juraj-hrivnak** [comment]
I have finally reported it. https://github.com/CleanroomMC/Tabulator/issues/1

**Comment by juraj-hrivnak** [comment]
Fixed in 3.0.3
