### ISSUE TITLE
ClientTicks queue overflow freeze/crash

### ISSUE THREAD

**Issue by KaleThyself** [juraj-hrivnak/Underdog#64]
### Description

While performing typical gameplay and re-activating a faucet after taking an ingot out of the smeltery, my instance completely froze up. 

*_08/11_
It can happen multiple times during gameplay, but from what I've noticed, it only occurs in my tinker's construct area. Oddly, the issue doesn't appear to affect my friend who is nearby. The additional mod I have added is the SerializationIsBad mod and the mod I disabled is OptionsEnforcer. 

### The latest.log file

https://mclo.gs/WdirC4X

### Underdog version

v.3.4.1

### Launcher

Prism Launcher

### OS

Windows

**Comment by juraj-hrivnak** [comment]
It is related to the [ClientTicks](https://github.com/SilentChaos512/SilentLib/blob/dd113cfee7309338cc2abc47412d0c00dea6f15a/src/main/java/net/silentchaos512/lib/event/ClientTicks.java#L62-L67) class from Silent Lib [here](https://mclo.gs/WdirC4X#L19697).
