### ISSUE TITLE
Weird tree gen

### ISSUE THREAD

**Issue by iEatShadows** [juraj-hrivnak/Underdog#65]
### Description

![tree](https://github.com/juraj-hrivnak/Underdog/assets/77649132/50b16434-3dec-4c0f-acec-67433bb44a42)

### The latest.log file

no need

### Underdog version

3.4.1

### Launcher

Prism Launcher

### OS

Windows

**Comment by juraj-hrivnak** [comment]
This is just what baobab trees look like.
That missing texture is a bug, though.
