### ISSUE TITLE
Mob Agression is set incorrectly 

### ISSUE THREAD

**Issue by Mementh** [juraj-hrivnak/Underdog#9]
as we talked in discord, the mob aggression is set too high.
# List of passive mobs (by entity id) that are made "neutral" like wolves.
    # You may put a tilde (~) in front of any entity id to make it specific; specific entity ids
    # will not count any entities extending (i.e., based on) the specified entity.
    # Additional number after the entity id is the chance (

# Additional number after the entity id is the chance (0.0 to 1.0) for entities of that type to spawn with the AI.

valid levels are 0.00 - 1.00 = 100 levels
if your wanting a 10% chance then a animal would need 0.10
a 1% chance would be 0.01 

this means 
animania:rooster_leghorn 0.7
animania:rooster_orpington 0.7
animania:rooster_plymouth_rock 0.7
animania:rooster_rhode_island_red 0.7
animania:rooster_wyandotte 0.7
thats 70% chance\
for the mob to be aggressive.

horse_colors:horse_felinoid 0.3
thats 30% chance for aggressive 

:) hope it helps :) cause i hate getting beaten up by roosters :)

EDIT: my derp, the % chance is for being passive.. so its a 70% chance to be passive, 30% to be aggressive. which is still higher than you planned..

**Comment by juraj-hrivnak** [comment]
`depacify_aggressive_chance` is now `0.05` instead of `0.1`
Closing.
